name = "TensorRenormalizationGroup"
uuid = "038389bf-03c2-461b-b4ee-e08046f5bcae"
version = "1.0.0-DEV"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
LinearAlgebra = "1"
OMEinsum = "0.9"
Zygote = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
